services:
  # --- 服务组1 ---
  frontend:
    build: 
      context: new-ai-handwash-APK
    ports:
      - "8080:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
      - ai

  backend:
    build: 
      context: ai-handwash-assist-server-main
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  ai:
    build: 
      context: new-ai-handwash-server
    ports:
      - "9500:9500"
    restart: always
    networks:
      - app-network

  # --- 服务组2  ---
  # frontend1:
  #   build:
  #     context: new-ai-handwash-APK
  #   ports:
  #     - "8081:80"
  #   restart: always
  #   networks:
  #     - app-network
  #   depends_on:
  #     - backend1
  #     - ai1

  # backend1:
  #   build:
  #     context: ai-handwash-assist-server-main
  #   ports:
  #     - "3001:3000"
  #   restart: always
  #   networks:
  #     - app-network

  # ai1:
  #   build:
  #     context: new-ai-handwash-server
  #   ports:
  #     - "9501:9500"
  #   restart: always
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge